### ISSUE TITLE
Mail Not Sending

### ISSUE THREAD

**Issue by bathe** [zene22/keycloak-spi-example#2]
I have followed all instructions and deployed module on Wildfly 11 with Keycloak 10.0.0. I have also added it as new execution. and email server is configured correctly in keycloak admin.

![image](https://user-images.githubusercontent.com/9054915/90671258-11bd7700-e272-11ea-86b8-52f412e7df85.png)

I am expecting that after adding this module, when new user is registered admin will get email.  but it is not sending the same. 
I observed that validate and success methods are not called at all.

Please advice.

**Comment by bathe** [comment]
Sorry I forgot to bind new workflow to registeruser activity.

**Comment by zene22** [comment]
Ok, no worries. I was just up to install a test environment to check. Glad to hear you succeeded. Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Shirish Bathe <notifications@github.com> Datum: 20.08.20  16:51  (GMT+01:00) An: zene22/keycloak-spi-example <keycloak-spi-example@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [zene22/keycloak-spi-example] Mail Not Sending (#2) 
Sorry I forgot to bind new workflow to registeruser activity.
